import { Inter } from 'next/font/google'
import './globals.css'
import CanvasComponent from './componenets/canvabg'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-900">

        {children}
      <CanvasComponent  />

      </body>
    </html>
  )
}
